<a href="https://colab.research.google.com/github/Rutvikaneriya23/DADV/blob/main/DADV_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as py
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
Data = pd.read_excel("/content/Car Inventory_DADV_2024.xlsx")

In [ ]:

Data.head() #top 5 rows

   Unnamed: 0    Make    Model   Color  Mileage  Price  Cost
0         NaN   Honda   Accord  Silver   101354     20    15
1         NaN  Toyota    Camry   Black    75006     25    20
2         NaN  Nissan   Altima   Green    69847     30    30
3         NaN  Nissan   Altima   Green    55233     30    25
4         NaN  Toyota  Corolla   Black    87278     30    20

In [ ]:
Data.head(8) #8 rows from start

   Unnamed: 0    Make    Model   Color  Mileage  Price  Cost
0         NaN   Honda   Accord  Silver   101354     20    15
1         NaN  Toyota    Camry   Black    75006     25    20
2         NaN  Nissan   Altima   Green    69847     30    30
3         NaN  Nissan   Altima   Green    55233     30    25
4         NaN  Toyota  Corolla   Black    87278     30    20
5         NaN  Toyota  Corolla    Blue   130684     20    15
6         NaN  Toyota  Corolla  Silver    59169    250    27
7         NaN   Honda    Civic   White   138789     20    10

In [ ]:
Data.tail() #last 5 rows

    Unnamed: 0    Make    Model   Color  Mileage  Price  Cost
17         NaN  Nissan   Maxima     Red   101856     30    25
18         NaN    Ford   Fusion   Black    42542     25    20
19         NaN   Dodge  Charger  Silver    34853     45    35
20         NaN   Dodge  Charger  Silver    58173     45    40
21         NaN   Dodge  Charger   Black   136775     20    18

In [ ]:
Data.tail(8) #last 8 rows

    Unnamed: 0    Make    Model   Color  Mileage  Price  Cost
14         NaN    Ford   Escape     Red    40826     40    40
15         NaN    Ford  Mustang  Silver    41560     30    30
16         NaN   Honda      CRV    Blue    49326     50    40
17         NaN  Nissan   Maxima     Red   101856     30    25
18         NaN    Ford   Fusion   Black    42542     25    20
19         NaN   Dodge  Charger  Silver    34853     45    35
20         NaN   Dodge  Charger  Silver    58173     45    40
21         NaN   Dodge  Charger   Black   136775     20    18

In [ ]:
Data.shape  # shows total rows and column number

(22, 7)

In [ ]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  0 non-null      float64
 1   Make        22 non-null     object
 2   Model       22 non-null     object
 3   Color       22 non-null     object
 4   Mileage     22 non-null     int64
 5   Price       22 non-null     int64
 6   Cost        22 non-null     int64
dtypes: float64(1), int64(3), object(3)
memory usage: 1.3+ KB

In [ ]:
Data.isnull().sum()

Unnamed: 0    22
Make           0
Model          0
Color          0
Mileage        0
Price          0
Cost           0
dtype: int64

In [ ]:
Data.nunique()

Unnamed: 0     0
Make           6
Model         15
Color          6
Mileage       22
Price          7
Cost           9
dtype: int64