<a href="https://colab.research.google.com/github/Rutvikaneriya23/DADV/blob/main/Practical_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df=pd.read_csv('/content/PlayCricket-6.csv')
df

     outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no

In [4]:
df.shape

(14, 5)

In [5]:
df.isnull().sum()

outlook     0
temp        0
humidity    0
windy       0
play        0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   outlook   14 non-null     object
 1   temp      14 non-null     object
 2   humidity  14 non-null     object
 3   windy     14 non-null     bool
 4   play      14 non-null     object
dtypes: bool(1), object(4)
memory usage: 594.0+ bytes

In [7]:
df.describe()

       outlook  temp humidity  windy play
count       14    14       14     14   14
unique       3     3        2      2    2
top      sunny  mild     high  False  yes
freq         5     6        7      8    9

In [23]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [24]:
df['outlook_n']=le.fit_transform(df['outlook'])
df['temp_n']=le.fit_transform(df['temp'])
df['humidity_n']=le.fit_transform(df['humidity'])
df['windy_n']=le.fit_transform(df['windy'])
df['play_n']=le.fit_transform(df['play'])
df

KeyError: 'outlook'

In [26]:
df=pd.read_csv('/content/PlayCricket-6.csv') # Re-load the data
df['outlook_n']=le.fit_transform(df['outlook'])
df['temp_n']=le.fit_transform(df['temp'])
df['humidity_n']=le.fit_transform(df['humidity'])
df['windy_n']=le.fit_transform(df['windy'])
df['play_n']=le.fit_transform(df['play'])
df

,outlook,temp,humidity,windy,play,outlook_n,temp_n,humidity_n,windy_n,play_n
0,sunny,hot,high,False,no,2,1,0,0,0
1,sunny,hot,high,True,no,2,1,0,1,0
2,overcast,hot,high,False,yes,0,1,0,0,1
3,rainy,mild,high,False,yes,1,2,0,0,1
4,rainy,cool,normal,False,yes,1,0,1,0,1
5,rainy,cool,normal,True,no,1,0,1,1,0
6,overcast,cool,normal,True,yes,0,0,1,1,1
7,sunny,mild,high,False,no,2,2,0,0,0
8,sunny,cool,normal,False,yes,2,0,1,0,1
9,rainy,mild,normal,False,yes,1,2,1,0,1
10,sunny,mild,normal,True,yes,2,2,1,1,1
11,overcast,mild,high,True,yes,0,2,0,1,1
12,overcast,hot,normal,False,yes,0,1,1,0,1
13,rainy,mild,high,True,no,1,2,0,1,0

In [27]:
df=df.drop(['outlook','temp','humidity','windy','play'],axis='columns')
df

    outlook_n  temp_n  humidity_n  windy_n  play_n
0           2       1           0        0       0
1           2       1           0        1       0
2           0       1           0        0       1
3           1       2           0        0       1
4           1       0           1        0       1
5           1       0           1        1       0
6           0       0           1        1       1
7           2       2           0        0       0
8           2       0           1        0       1
9           1       2           1        0       1
10          2       2           1        1       1
11          0       2           0        1       1
12          0       1           1        0       1
13          1       2           0        1       0

In [28]:
x=df.drop('play_n',axis='columns')
y=df['play_n']

In [29]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(x,y)

DecisionTreeClassifier()

In [30]:
model.predict([[2,1,0,0]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])